# Generated by Django 4.1.1 on 2023-04-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='naturalconvection',
            old_name='predicted_output',
            new_name='experimental_output',
        ),
        migrations.AddField(
            model_name='naturalconvection',
            name='theoritical_output',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
